/* Summary: The section has a blurred radial gradient background and a call-to-action (CTA) content block.
It is centered on the page and includes a gradient-based title, a subtitle, a paragraph of text, and a button with a gradient background.
*/

Vue.component("purple_background_cta_component_1724092527", {
    template: `
    <section id="cta-section-container">
        <div id="section-container" class="max-w-6xl mx-auto px-4 sm:px-6 bg-white"><div id="content-container" class="relative px-8 py-12 md:py-20 rounded-[3rem] overflow-hidden" style=""><div id="radial-gradient" aria-hidden="true" class="absolute flex items-center justify-center top-0 -translate-y-1/2 left-1/2 -translate-x-1/2 pointer-events-none -z-10 w-1/3 aspect-square"><div id="radial-gradient-outer" class="bg-red-500 absolute inset-0 translate-z-0 rounded-full blur-[120px] opacity-70"></div> <div id="radial-gradient-inner" class="absolute w-1/4 h-1/4 translate-z-0 rounded-full blur-[40px] bg-red-400"></div></div> <div id="blurred-shape" aria-hidden="true" class="absolute bottom-0 translate-y-1/2 left-0 blur-2xl opacity-50 pointer-events-none -z-10"><svg xmlns="http://www.w3.org/2000/svg" width="434" height="427"><defs><linearGradient id="bs5-a" x1="19.609%" x2="50%" y1="14.544%" y2="100%"><stop offset="0%" class="#EF4444"></stop><stop offset="100%" stop-opacity="0" class="DC2626"></stop></linearGradient></defs>  / contenteditable="true"&gt;
                    </svg></div> <div id="content" class="max-w-3xl mx-auto text-center"><div id="content-subtitle" class="flex"><div id="content-subtitle-text" data-mf-new="true" class="flex-1 font-medium bg-clip-text pb-3 text-transparent bg-gradient-to-r from-red-500 to-red-200" style="">Dive into a World of Magical Mischief!</div></div> <div id="content-title-container" class="flex"><h2 id="content-title" data-mf-new="true" class="flex-1 h2 bg-clip-text pb-4 bg-gradient-to-r from-slate-200/60 via-slate-200 to-slate-200/60" style="">Pixelated Wonders await you!</h2></div> <div id="content-body-container" class="flex"><p id="content-body" class="flex-1 text-lg mb-8 text-slate-400" style="">Embark on an epic quest to collect, trade, and conquer with our spellbinding digital sprites!</p></div> <a id="content-cta-button" href="#0" class="btn transition duration-150 ease-in-out group text-slate-900 bg-gradient-to-r from-white/80 via-white to-white/80 hover:bg-white">Unleash the Magic <span id="content-cta-arrow" class="tracking-normal group-hover:translate-x-0.5 transition-transform duration-150 ease-in-out ml-1 text-red-500">-&gt;</span></a></div></div></div> <div id="radial-gradient-inner" class="absolute w-1/4 h-1/4 translate-z-0 rounded-full blur-[40px] bg-red-400"></div></div> <div id="blurred-shape" aria-hidden="true" class="absolute bottom-0 translate-y-1/2 left-0 blur-2xl opacity-50 pointer-events-none -z-10"><svg xmlns="http://www.w3.org/2000/svg" width="434" height="427"><defs><linearGradient id="bs5-a" x1="19.609%" x2="50%" y1="14.544%" y2="100%"><stop offset="0%" class="#EF4444"></stop><stop offset="100%" stop-opacity="0" class="DC2626"></stop></linearGradient></defs>  / contenteditable="true"&gt;
                    </svg></div> <div id="content" class="max-w-3xl mx-auto text-center"><div id="content-subtitle" class="flex"><div id="content-subtitle-text" data-mf-new="true" class="flex-1 font-medium bg-clip-text pb-3 text-transparent bg-gradient-to-r from-red-500 to-red-200" style="">Dive into a World of Magical Mischief!</div></div> <div id="content-title-container" class="flex"><h2 id="content-title" data-mf-new="true" class="flex-1 h2 bg-clip-text pb-4 bg-gradient-to-r from-slate-200/60 via-slate-200 to-slate-200/60" style="">Pixelated Wonders Await</h2></div> <div id="content-body-container" class="flex"><p id="content-body" class="flex-1 text-lg mb-8 text-slate-400" style="">Embark on an epic quest to collect, trade, and conquer with our spellbinding digital sprites!</p></div> <a id="content-cta-button" href="#0" class="btn transition duration-150 ease-in-out group text-slate-900 bg-gradient-to-r from-white/80 via-white to-white/80 hover:bg-white">Unleash the Magic <span id="content-cta-arrow" class="tracking-normal group-hover:translate-x-0.5 transition-transform duration-150 ease-in-out ml-1 text-red-500">-&gt;</span></a></div></div></div> <div id="radial-gradient-inner" class="absolute w-1/4 h-1/4 translate-z-0 rounded-full blur-[40px] bg-red-400"></div></div> <div id="blurred-shape" aria-hidden="true" class="absolute bottom-0 translate-y-1/2 left-0 blur-2xl opacity-50 pointer-events-none -z-10"><svg xmlns="http://www.w3.org/2000/svg" width="434" height="427"><defs><linearGradient id="bs5-a" x1="19.609%" x2="50%" y1="14.544%" y2="100%"><stop offset="0%" class="#EF4444"></stop><stop offset="100%" stop-opacity="0" class="DC2626"></stop></linearGradient></defs>  / contenteditable="true"&gt;
                    </svg></div> <div id="content" class="max-w-3xl mx-auto text-center"><div id="content-subtitle" class="flex"><div id="content-subtitle-text" class="flex-1 font-medium bg-clip-text pb-3 text-transparent bg-gradient-to-r from-red-500 to-red-200" style="" data-mf-new="true">Dive into a World of Magical Mischief!</div></div> <div id="content-title-container" class="flex"><h2 id="content-title" class="flex-1 h2 bg-clip-text pb-4 bg-gradient-to-r from-slate-200/60 via-slate-200 to-slate-200/60" style="" data-mf-new="true">Pixelated Wonders Await you!</h2></div> <div id="content-body-container" class="flex"><p id="content-body" class="flex-1 text-lg mb-8 text-slate-400" style="">Embark on an epic quest to collect, trade, and conquer with our spellbinding digital sprites!</p></div> <a id="content-cta-button" href="#0" class="btn transition duration-150 ease-in-out group text-slate-900 bg-gradient-to-r from-white/80 via-white to-white/80 hover:bg-white">Unleash the Magic <span id="content-cta-arrow" class="tracking-normal group-hover:translate-x-0.5 transition-transform duration-150 ease-in-out ml-1 text-red-500">-&gt;</span></a></div></div></div>
                    <div id="radial-gradient-inner" class="absolute w-1/4 h-1/4 translate-z-0 rounded-full blur-[40px] bg-red-400">
                    </div>
                </div>
                <!-- Blurred shape -->
                <div id="blurred-shape" class="absolute bottom-0 translate-y-1/2 left-0 blur-2xl opacity-50 pointer-events-none -z-10" aria-hidden="true">
                    <svg xmlns="http://www.w3.org/2000/svg" width="434" height="427">
                        <defs><linearGradient id="bs5-a" x1="19.609%" x2="50%" y1="14.544%" y2="100%"><stop offset="0%" class="#EF4444" /><stop offset="100%" class="DC2626" stop-opacity="0" /></linearGradient></defs>
                        <path fill="url(#bs5-a)" fill-rule="evenodd" d="m0 0 461 369-284 58z" transform="matrix(1 0 0 -1 0 427)" />
                    </svg>
                </div>
                <!-- Content -->
                <div id="content" class="max-w-3xl mx-auto text-center">
                    <div id="content-subtitle" class="flex"><div id="content-subtitle-text" class="flex-1 font-medium bg-clip-text pb-3 text-transparent bg-gradient-to-r from-red-500 to-red-200">Dive into a World of Magical Mischief!</div></div>
                    <div class="flex" id="content-title-container"><h2 id="content-title" class="flex-1 h2 bg-clip-text pb-4 bg-gradient-to-r from-slate-200/60 via-slate-200 to-slate-200/60">Pixelated Wonders Await Your Command!</h2></div>
                    <div class="flex" id="content-body-container"><p id="content-body" class="flex-1 text-lg mb-8 text-slate-400">Embark on an epic quest to collect, trade, and conquer with our spellbinding digital sprites!</p></div>
                    <a id="content-cta-button" href="#0" class="btn transition duration-150 ease-in-out group text-slate-900 bg-gradient-to-r from-white/80 via-white to-white/80 hover:bg-white">Unleash the Magic <span id="content-cta-arrow" class="tracking-normal group-hover:translate-x-0.5 transition-transform duration-150 ease-in-out ml-1 text-red-500">-&gt;</span></a>
                </div>
            </div>
        </div>
    </section>`,
        data() {
            return {
                expanded: false, 
                tab: null,
            };
        },
    });
                    